---
- hosts: localhost
  tasks:
    - name: Remove gitea-prod release
      kubernetes.core.helm:
        name: gitea-prod
        release_namespace: default
        state: absent
        wait: true
    - name: Remove kubernetes python package
      pip:
        name: kubernetes
        state: absent