apiVersion: v1
kind: Secret
metadata:
  name: gitea-db-secret
  namespace: default
type: Opaque
stringData:
  GITEA__DATABASE__USER: akash
  GITEA__DATABASE__PASSWORD: userpass
  GITEA__DATABASE__NAME: database_8935920
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: default    
  labels:
    app: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
      - name: gitea
        image: gitea/gitea:latest
        ports:
        - containerPort: 3000
        - containerPort: 22
        env:
        - name: USER_UID
          value: "1000"
        - name: USER_GID
          value: "1000"
        - name: GITEA__DATABASE__DB_TYPE
          value: "mysql"
        - name: GITEA__DATABASE__HOST
          value: "mysql:3306"
        - name: GITEA__DATABASE__USER
          valueFrom:
            secretKeyRef:
              name: gitea-db-secret
              key: GITEA__DATABASE__USER
        - name: GITEA__DATABASE__PASSWORD
          valueFrom:
            secretKeyRef:
              name: gitea-db-secret
              key: GITEA__DATABASE__PASSWORD
        - name: GITEA__DATABASE__NAME
          valueFrom:
            secretKeyRef:
              name: gitea-db-secret
              key: GITEA__DATABASE__NAME
        volumeMounts:
        - name: gitea-data
          mountPath: /data
      volumes:
      - name: gitea-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: gitea
  namespace: default      
spec:
  type: NodePort
  selector:
    app: gitea
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    nodePort: 30090
  - name: ssh
    port: 22
    targetPort: 22
    nodePort: 30022
