---
- name: Apply MySQL Kubernetes Deployment
  hosts: localhost
  connection: local  
  gather_facts: no    

  tasks:
    - name: Ensure kubernetes Python client is installed
      pip:
        name: kubernetes
        state: present

    - name: Apply MySQL deployment manifest
      kubernetes.core.k8s:
        state: present
        src: mysql.yaml

    - name: Apply Gitea manifest
      kubernetes.core.k8s:
        state: present
        src: gitea.yaml
